#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmspack
Version  : 0.6alpha
Release  : 7
URL      : https://www.cabextract.org.uk/libmspack/libmspack-0.6alpha.tar.gz
Source0  : https://www.cabextract.org.uk/libmspack/libmspack-0.6alpha.tar.gz
Summary  : Compressors and decompressors for Microsoft formats
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmspack-bin
Requires: libmspack-lib
Requires: libmspack-license
Patch1: cve-2018-14679.patch

%description
libmspack 0.6alpha
The purpose of libmspack is to provide compressors and decompressors,
archivers and dearchivers for Microsoft compression formats: CAB, CHM, WIM,
LIT, HLP, KWAJ and SZDD. It is also designed to be easily embeddable,
stable, robust and resource-efficient.

%package bin
Summary: bin components for the libmspack package.
Group: Binaries
Requires: libmspack-license

%description bin
bin components for the libmspack package.


%package dev
Summary: dev components for the libmspack package.
Group: Development
Requires: libmspack-lib
Requires: libmspack-bin
Provides: libmspack-devel

%description dev
dev components for the libmspack package.


%package lib
Summary: lib components for the libmspack package.
Group: Libraries
Requires: libmspack-license

%description lib
lib components for the libmspack package.


%package license
Summary: license components for the libmspack package.
Group: Default

%description license
license components for the libmspack package.


%prep
%setup -q -n libmspack-0.6alpha
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533224308
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533224308
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libmspack
cp COPYING.LIB %{buildroot}/usr/share/doc/libmspack/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cabrip
/usr/bin/chmextract
/usr/bin/msexpand
/usr/bin/oabextract

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libmspack.so
/usr/lib64/pkgconfig/libmspack.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmspack.so.0
/usr/lib64/libmspack.so.0.1.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libmspack/COPYING.LIB
